debug

diff --git a/build/pre-commit b/build/pre-commit
--- a/build/pre-commit
+++ b/build/pre-commit
@@ -10,20 +10,18 @@
 # Run pylint on the changed files
 function run_pylint () {
 return_code=0
-  if [ -d "./build/_build/_venv/lib/python3.8/site-packages/pylint" ]
+  if [ ! -d "./build/_build/_venv/lib/python3.8/site-packages/pylint" ]
   then
       make -e install_pylint
   fi
 
 for line in $changed_files
 do
-  #command="PYLINT_TARGET=$line make -e pylint_raw"
   PYLINT_TARGET=$line make -e pylint_raw >pylint_report.tmp 2>&1
   ret=$?
 
   if [ "$ret" != "0" ]
   then
-      #echo "PYLINT_FAILED: ${command}"
       cat pylint_report.tmp
       return_code=1
   fi
@@ -31,9 +29,10 @@ done
 
 if [ "$return_code" != "0" ]
 then
+  echo "FAILURE: PRE-COMMIT HOOK FAILED!!!"
   exit $return_code
 fi
-echo "SUCCESS!!!"
+
 }
 
 changed_files=$(git diff --diff-filter=d --name-only HEAD| grep '.*\.py$')
@@ -59,7 +58,6 @@ allownonascii=$(git config --type=bool hooks.allownonascii)
 
 # Redirect output to stderr.
 exec 1>&2
-
 # Cross platform projects tend to avoid non-ASCII filenames; prevent
 # them from being added to the repository. We exploit the fact that the
 # printable range starts at the space character and ends with tilde.
@@ -83,6 +81,15 @@ If you know what you are doing you can disable this check using:
 EOF
 	exit 1
 fi
-
+echo "$against"
 # If there are whitespace errors, print the offending file names and fail.
-exec git diff-index --check --cached $against --
+git diff-index --check --cached $against --
+ret=$?
+
+if [ "$ret" != "0" ]
+then
+echo "FAILURE: PRE-COMMIT HOOK FAILED!!!"
+exit $ret
+fi
+
+echo "SUCCESS: PRE-COMMIT HOOK SUCCEED!!!"
